# This is a basic workflow to help you get started with Actions

name: reviewdog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  vimlint:
    name: runner / vimlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bb010g/reviewdog-action-vimlint@v1
        with:
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
          # If you want to ignore EVL103 for any cases and EVL102 for variable `_`:
          flags: '-e EVL103=1 -e EVL102.l:_=1'
