# This is a basic workflow to help you get started with Actions

name: reviewdog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vint:
    name: runner / vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: vint
        uses: reviewdog/action-vint@v1
        with:
          level: info
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter. 
